services:
  - type: web
    name: tanglish-caption-api
    runtime: docker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: TRACKER_EMAIL
        sync: false
      - key: GEMINI_API_KEY_1
        sync: false
      - key: GEMINI_API_KEY_2
        sync: false
      - key: GEMINI_API_KEY_3
        sync: false
      - key: GEMINI_API_KEY_4
        sync: false
      - key: GEMINI_API_KEY_5
        sync: false
      - key: GEMINI_API_KEY_6
        sync: false
      - key: GEMINI_API_KEY_7
        sync: false
      - key: GEMINI_API_KEY_8
        sync: false
      - key: GEMINI_API_KEY_9
        sync: false
      - key: GEMINI_API_KEY_10
        sync: false
      - key: GEMINI_API_KEY_11
        sync: false
